@url = http://localhost:8080/bot
@contentType = application/json
@now = {{$localDatetime 'YYYY-MM-DDThh:mm:ss.msZ' 3 h}}
@userId = {{$dotenv ADMIN_USER_ID}}

###
# PINGイベント
POST {{url}}
Content-Type: {{contentType}}
X-TRAQ-BOT-TOKEN: {{$dotenv BOT_VERIFICATION_TOKEN}}
X-TRAQ-BOT-EVENT: PING

{
  "eventTime": "{{now}}"
}

###
# メンション無しで投稿

@message = 無限

POST {{url}}
Content-Type: {{contentType}}
X-TRAQ-BOT-TOKEN: {{$dotenv BOT_VERIFICATION_TOKEN}}
X-TRAQ-BOT-EVENT: MESSAGE_CREATED

{
  "eventTime": "{{now}}",
  "message": {
    "id": "{{$guid}}",
    "user": {
      "id": "{{userId}}",
      "name": "ikura-hamu",
      "displayName": "いくら・はむ",
      "iconId": "{{$guid}}",
      "bot": false
    },
    "channelId": "{{$guid}}",
    "text": "{{message}}",
    "plainText": "{{message}}",
    "embedded": [],
    "createdAt": "{{now}}",
    "updatedAt": "{{now}}"
  }
}

###
# メンションして投稿

@mentionMessage = にゃん

POST {{url}}
Content-Type: {{contentType}}
X-TRAQ-BOT-TOKEN: {{$dotenv BOT_VERIFICATION_TOKEN}}
X-TRAQ-BOT-EVENT: MESSAGE_CREATED

{
  "eventTime": "{{now}}",
  "message": {
    "id": "{{$guid}}",
    "user": {
      "id": "{{userId}}",
      "name": "ikura-hamu",
      "displayName": "いくら・はむ",
      "iconId": "{{$guid}}",
      "bot": false
    },
    "channelId": "{{$guid}}",
    "text": "{{mentionMessage}}",
    "plainText": "{{mentionMessage}}",
    "embedded": [
      {
        "raw": "@BOT_ikura-hamu",
        "type": "user",
        "id": "{{$dotenv BOT_USER_ID}}"
      }
    ],
    "createdAt": "{{now}}",
    "updatedAt": "{{now}}"
  }
}